CREATE TABLE notes (
    -- UNIQUEIDENTIFIER is SQL Server's UUID. The value is generated by the
    -- application (GenerationType.UUID), not by NEWID(), so the POST response
    -- carries the id without a re-read.
    id         UNIQUEIDENTIFIER NOT NULL,

    -- NVARCHAR, not VARCHAR. On SQL Server VARCHAR is single-byte and tied to
    -- the database collation, so a non-Latin title silently becomes question
    -- marks. NVARCHAR is UTF-16 and just works. The entity pairs this with
    -- @Nationalized so Hibernate's `validate` agrees.
    title      NVARCHAR(200)    NOT NULL,

    -- BIT is the boolean. There is no BOOLEAN type.
    done       BIT              NOT NULL CONSTRAINT DF_notes_done DEFAULT (0),

    -- DATETIME2(6) and not DATETIMEOFFSET. The column stores an Instant, which
    -- is already UTC, so an offset would be a second representation of
    -- information that cannot vary. (6) matches Hibernate's default precision
    -- for a TIMESTAMP mapping -- leave it off and `validate` compares
    -- datetime2(7) against datetime2(6).
    created_at DATETIME2(6)     NOT NULL,

    -- NONCLUSTERED is the deliberate part. SQL Server clusters the primary key
    -- by default, and a clustered index on a random UUID means every insert
    -- lands in the middle of the B-tree: page splits and fragmentation from the
    -- first thousand rows. Cheap to get right now, painful to change later.
    CONSTRAINT PK_notes PRIMARY KEY NONCLUSTERED (id)
);

-- The list endpoint's only ordering, and the clustered index because inserts
-- are append-ordered by time. This is the layout the table is actually read in.
CREATE CLUSTERED INDEX IX_notes_created_at ON notes (created_at DESC);
